name: Publish

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install and build
        uses: actions/checkout@v1
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
        run: |
          yarn install --frozen-lock-file
          yarn build

      - name: Build demo page
        working-directory: example
        run: |
          yarn install --frozen-lock-file
          yarn build
        
      - name: Deploy demo page
        uses: JamesIves/github-pages-deploy-action@3.7.1
        working-directory: example
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages 
          FOLDER: dist 
          CLEAN: true
      
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
